name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Validate Gradle Wrapper 
      uses: gradle/wrapper-validation-action@v3
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '16'

    - name: Run Yarn Install
      run: |
            yarn install 
      
    - name: Grant execute permission for gradlew
      run: |
            cd android
            chmod +x gradlew
            
    - name: Build with Gradle
      run: |
            cd android
            ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: "android_build"
        path: ./android/app/build/outputs/apk/release/app-release.apk
        retention-days: 1
